name: Build from Dockerfile
on:
  push:
  pull_request:
  schedule:
    - cron: "33 3 * * 3"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      IMAGE_NAME: cert-generator
      REGISTRY: ghcr.io/altinn
    steps:
    - name: Clone the repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Buildah Action
      id: build-image
      uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./Dockerfile

    - name: Log in to the GitHub Container registry
      uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GitHub Container Repository
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.REGISTRY }}
